### ISSUE TITLE
Fix: 특정 시간대 CPU사용률 급증하는  문제

### ISSUE THREAD

**Issue by Munhangyeol** [ICT-Dev-Route/Dev-Route-BE#125]
###  현황
**Prometheus**와 **Grafana**를 이용해서 모니터링을 하는 중 다음처럼  10월 9일 22시 48분 경에 **CPU사용률**이 97%에 육박하는 것을 발견
또한 ram으로 데이터를 올리는 **page-in**  과 데이터를 ram으로 내리는 **page-out** 도 매우 높은 것을 발견함 

<img src="https://github.com/user-attachments/assets/a25d4450-d40a-49d4-a00a-37f3b9d1781c" width="600" height="300"/>
<img width="527" alt="image" src="https://github.com/user-attachments/assets/3003abad-a146-4e6f-a78d-20912f73a78e">

이 외에도 2틀 혹은 하루에 한번 정도 cpu사용률 및 page-in, page-out을 비롯한 network-traffic, page-fault rate역시 모두 높은 시간대가 있는 것을 확인하고, **이 시간대에 자원 사용 패턴을 분석**하여, 어떤 애플리케이션이나 프로세스가 높은 부하를 유발하는지 파악할 필요가 있다고 판단.
## 버그 분석
우선 해당 시간대의 ec2 서버 의 로그를 확인 했는데, 별다른 이상이 없어서, docker내에서 해당 시간대의 log를 찍어보니 다음과 같은 결과가 발생함.
```
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:220)
at jdk.proxy2/jdk.proxy2.$Proxy174.findByName(Unknown Source)
at com.teamdevroute.devroute.recruitment.service.RecruitmentUpdateService.parseResponse(RecruitmentUpdateService.java:86)
at com.teamdevroute.devroute.recruitment.service.RecruitmentUpdateService.parseAndStoreRecruitment(RecruitmentUpdateService.java:69)
at com.teamdevroute.devroute.recruitment.service.RecruitmentUpdateService.fetchAndSaveJobs(RecruitmentUpdateService.java:58)
at com.teamdevroute.devroute.recruitment.service.RecruitmentUpdateService.fetchJobs(RecruitmentUpdateService.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

즉 Recruitment UpdateService과정에서 comanyName을 반환할 때 여러개의 company를 반환해서 오류가 생기는 것이었음
## 예상 결과

> CPU사용률이 저정도로 안올라가게 하고, recruitmentUpdateService가 잘 동작해야함

## 버그 fix 내용 

- CI/CD관련하여 docker에 캐싱을 통해서 빌드 시간 단축 및 cpu사용률 저하를 목표함
- dockerhub에서 pull후 docker에서 빌드시에 사용하는 cpu 사용률을 제어하여, cpu사용률을 저하시킴

### 

**CI/CD 시간 단축**

- 캐싱을 도입하기 전 ci/cd 시간
![](https://velog.velcdn.com/images/msw0909/post/164d5a70-b240-4e4c-bf01-97d598da2749/image.png)

- 캐싱을 도입하기 후 ci/cd시간
<img width="590" alt="image" src="https://github.com/user-attachments/assets/c9cd2210-080a-4db2-ad05-e4ac330b9ba9">

 기존 대비 55.37% 속도 개선

### **CPU 최대 사용률 감소**
<img width="433" alt="image" src="https://github.com/user-attachments/assets/eb22685c-ca81-4acf-b7c9-f71fce488af6">

약 53.6%의 CPU 사용률을 줄임

**Comment by mete0rfish** [comment]
정확히 어떤 과정에서 발생하는 문제일까요?

**Comment by Munhangyeol** [comment]
> 정확히 어떤 과정에서 발생하는 문제일까요?
현재 **```RecruitmentUpdateService```** 클래스 내에서 아래의 메서드가 cron작업이 되는데,

```java  @Scheduled(cron = "0 0 0 * * *", zone = "Asia/Seoul") 
// 매일 자정 업데이트
    public void fetchJobs() {
        for (SearchKeyWord keyword : SearchKeyWord.values()) {
            fetchAndSaveJobs(keyword.name());
        }
    }
```
이 함수 내에서 아래 처럼 company를 가지고 올 때
```java
 private Recruitment parseResponse(JsonNode jobNode, String keyword) {
       '''중략'''

        Company company = companyRepository.findByName(companyName).orElseGet(() -> {
            Company newCompany = Company.builder()
                    .name(companyName)
                    .recruitCount(0L)
                    .clickCount(0L)
                    .build();

            return companyRepository.save(newCompany);
        });
```
 company가 unique하지않고, 6개가 나와서 ```org.springframework.dao.IncorrectResultSizeDataAccessException: Query did not return a unique result: 6 results were returned``` 라는 로그가 찍히게 됩니다.

또한 이 메서드 내에는 **트렌젝션 처리**가 안 되어있습니다. 그래서 위에서 생긴 오류로 인해서 ```Transactional```처리할 때 오류가 생겨서 **db 락**이 걸려서 cpu 점유율이 올라갔나 라는 추측과 **사람인 api를 가지고 올 때의 과정**에서 cpu를 너무 많이 잡아 먹나.. 뭐 이런 생각도 하고있습니다. 아직 cpu가 정확히 왜 올라갔는지에 대해서는 몰라서 좀더 공부를 해봐야할 것 같아요 하하

**Comment by mete0rfish** [comment]
말씀 주신 `parseResponse`의 `CompanyRepositort.findByName()`의 리턴이 **다중 값으로 나오는 부분은 수정이 필요**해보이네요. 해당 부분은 Company의 name 필드의 `Unique 처리`를 통해 해결해보겠습니다.

**Comment by mete0rfish** [comment]
RDS의 클라우드 와치와 CPU 사용량 사진입니다.
<img width="1325" alt="image" src="https://github.com/user-attachments/assets/f136b266-ebf0-448f-9153-a236252d9210">
<img width="1098" alt="image" src="https://github.com/user-attachments/assets/32a27a40-c634-4911-8b39-00a8b35db0cd">

혹시 위 두가지의 지표가 이번 문제와 관련이 있을까요?

**Comment by Munhangyeol** [comment]
아아 저도 아직 정확히는 못찾았어요.. 근데 성원님 그라파나 대시보드에서 cpu사용률 97퍼가 된 저 시간때(10월 9일 10시 45분경)를 확인하니까 

<img width="940" alt="image" src="https://github.com/user-attachments/assets/39ef2179-693d-4e20-ae6d-7f9a1f4b6f58">

아예 그래프에서 사라져있더라고요. 그리고 아마 저때 제가 pr올린게 **CI/CD**해서 ec2에 올라가는 중이었던 것 같습니다.
제가 지금 추측하기로는 저 때 CI/CD로 올라 가는 시간과 , spring단에서 `fetch-job`을 통해서 `RecruitmentUpdate` 되는 부분에서 예외가 터진시간이 겹쳐서 아마 저 때 저랬지 않았나 싶습니다. 

혹시 

> RDS의 클라우드 와치와 CPU 사용량 사진입니다.

이 사진 몇일 사진인지 알 수 있을까요?🧐

**Comment by Munhangyeol** [comment]
<img width="868" alt="image" src="https://github.com/user-attachments/assets/d3137db3-262a-46c7-93fa-2879c4e54387">
이건 cpu사용량을 최대로 했을 때입니다.

**Comment by mete0rfish** [comment]
Company의 name필드의 unique 설정은 완료했습니다. 그러나 기존 데이터 중 name이 duplicate되는 튜플이 많아 Company와 Recruitment 테이블을 drop하는 건 어떨지요...??

**Comment by Munhangyeol** [comment]
이미 테이블에 들어가 있는 튜플이 많아서 drop하는 것도 괜찮을 것 같습니다!
